<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ruangan Ber-AC Bikin Kulit Kering Hingga _2f2875</name>
   <tag></tag>
   <elementGuidId>f1e44675-b4ed-4976-b658-df23025fa01e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11ec8b5b-1707-4119-be2b-6b507797f071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gs-title</value>
      <webElementGuid>9179327a-9ca4-43d3-9db0-d3e9c30381c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2022/09/16/112450228/ruangan-ber-ac-bikin-kulit-kering-hingga-picu-penuaan-dini-ini-solusinya&amp;sa=U&amp;ved=2ahUKEwj6ldjduuGDAxWJxTgGHTanCboQFnoECAkQAg&amp;usg=AOvVaw2cWNTvzzynbpcUbEx5DMlG</value>
      <webElementGuid>1b5e7aa2-6aa7-4481-8c76-8a45128f636f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>1478807c-58bf-4b17-a1eb-cc204aec2b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>7e37e846-fab1-41ec-93fd-24aaa2fbb684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2022/09/16/112450228/ruangan-ber-ac-bikin-kulit-kering-hingga-picu-penuaan-dini-ini-solusinya&amp;sa=U&amp;ved=2ahUKEwj6ldjduuGDAxWJxTgGHTanCboQFnoECAkQAg&amp;usg=AOvVaw2cWNTvzzynbpcUbEx5DMlG</value>
      <webElementGuid>903e835e-04ca-47dd-9f79-fd1b91427559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ctorig</name>
      <type>Main</type>
      <value>https://biz.kompas.com/read/2022/09/16/112450228/ruangan-ber-ac-bikin-kulit-kering-hingga-picu-penuaan-dini-ini-solusinya</value>
      <webElementGuid>69ea8b8f-6eb0-4eee-90bb-07d3a9352b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ruangan Ber-AC Bikin Kulit Kering Hingga Picu Penuaan Dini, Ini ...</value>
      <webElementGuid>ec5ca9e0-290d-4469-92cb-671b08ba9cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;___gcse_0&quot;)/div[@class=&quot;gsc-control-cse gsc-control-cse-en&quot;]/div[@class=&quot;gsc-control-wrapper-cse&quot;]/div[@class=&quot;gsc-results-wrapper-nooverlay gsc-results-wrapper-visible&quot;]/div[@class=&quot;gsc-wrapper&quot;]/div[@class=&quot;gsc-resultsbox-visible&quot;]/div[@class=&quot;gsc-resultsRoot gsc-tabData gsc-tabdActive&quot;]/div[@class=&quot;gsc-results gsc-webResult&quot;]/div[@class=&quot;gsc-expansionArea&quot;]/div[@class=&quot;gsc-webResult gsc-result&quot;]/div[@class=&quot;gs-webResult gs-result&quot;]/div[@class=&quot;gsc-thumbnail-inside&quot;]/div[@class=&quot;gs-title&quot;]/a[@class=&quot;gs-title&quot;]</value>
      <webElementGuid>a1325dbb-2f78-411a-b2d2-0cd6eb1f5d30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='___gcse_0']/div/div/div/div[5]/div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>bd5f8803-caaf-4717-a122-41ec2c9091db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ber'])[3]/following::a[1]</value>
      <webElementGuid>f0029b91-2bfb-45d5-ad34-a5d0bec71fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='biz.kompas.com'])[1]/preceding::a[1]</value>
      <webElementGuid>9d10bd23-3a2e-4e9a-82af-3ead2a6a4968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ruangan']/parent::*</value>
      <webElementGuid>d3043b1c-017f-4dcb-bec5-0b20e8687fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2022/09/16/112450228/ruangan-ber-ac-bikin-kulit-kering-hingga-picu-penuaan-dini-ini-solusinya&amp;sa=U&amp;ved=2ahUKEwj6ldjduuGDAxWJxTgGHTanCboQFnoECAkQAg&amp;usg=AOvVaw2cWNTvzzynbpcUbEx5DMlG')]</value>
      <webElementGuid>3d438855-9806-48f3-9493-ffc308afb92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a</value>
      <webElementGuid>6e8d0880-5e1f-43b3-9ba8-89c019e29505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.google.com/url?client=internal-element-cse&amp;cx=partner-pub-9012468469771973:uc7pie-r3ad&amp;q=https://biz.kompas.com/read/2022/09/16/112450228/ruangan-ber-ac-bikin-kulit-kering-hingga-picu-penuaan-dini-ini-solusinya&amp;sa=U&amp;ved=2ahUKEwj6ldjduuGDAxWJxTgGHTanCboQFnoECAkQAg&amp;usg=AOvVaw2cWNTvzzynbpcUbEx5DMlG' and (text() = 'Ruangan Ber-AC Bikin Kulit Kering Hingga Picu Penuaan Dini, Ini ...' or . = 'Ruangan Ber-AC Bikin Kulit Kering Hingga Picu Penuaan Dini, Ini ...')]</value>
      <webElementGuid>01ca2b36-bdde-4dfa-b3dc-980ea95beab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
