<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Contact Us_icoBase icoClosePopup</name>
   <tag></tag>
   <elementGuidId>1bd47302-3c41-4ffb-a107-a49470b21159</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icoBase.icoClosePopup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bf8f056a-551d-4d27-b45d-4eb3c800d132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icoBase icoClosePopup</value>
      <webElementGuid>e666bc26-aa25-4989-84f4-ced15bb7c06a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js csstransitions&quot;]/body[@class=&quot;revampV2&quot;]/div[@class=&quot;popup-kcmplus&quot;]/button[@class=&quot;popup-close&quot;]/span[@class=&quot;icoBase icoClosePopup&quot;]</value>
      <webElementGuid>a8de7ba7-444a-42e9-851b-494060ce7189</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>88ead32b-6726-49b1-8921-1699ac5480b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
