<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lanjutkan</name>
   <tag></tag>
   <elementGuidId>691f9605-20f6-489e-82f8-d0d004a60621</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Lanjutkan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b473ae87-26ef-44ba-920b-978a0d437be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.kompas.com/?lgn_method=kompasid&amp;_ga=2.55894827.1868958925.1705392562-12342931.1705392559</value>
      <webElementGuid>a88feee8-aabd-4507-a62b-259dd43304f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>68c9b961-3df5-47f6-be11-5a4fd4094f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;block-footer&quot;]/div[@class=&quot;text-center&quot;]/p[1]/a[1]</value>
      <webElementGuid>71c7bd0a-a0c2-4b7a-a70b-87e5460365d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lanjutkan')]</value>
      <webElementGuid>63fb8f51-4273-4f10-a624-51b2d1322ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>ae41ca2b-2515-4118-951c-8396972a3ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.kompas.com/?lgn_method=kompasid&amp;_ga=2.55894827.1868958925.1705392562-12342931.1705392559')]</value>
      <webElementGuid>556f7efc-e592-4228-87f4-631a2d7c077b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1c28806d-590d-4198-8a16-41ac9017d839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.kompas.com/?lgn_method=kompasid&amp;_ga=2.55894827.1868958925.1705392562-12342931.1705392559' and (text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>dcd38a33-fb6b-4fc6-a4c6-bd3cfdd4dad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
